Category:
    type: entity
    table: category
    repositoryClass: CategoryRepository
    id:
        id:
            type: integer
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            length: 255

    oneToMany:
        posts:
            targetEntity: Post
            mappedBy: category
#            orphanRemoval: true