Post:
    type: entity
    table: post
    repositoryClass: PostRepository
    id:
        id:
            type: integer
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            length: 255
        content:
            type: text

    manyToOne:
        category:
            targetEntity: Category
            inversedBy: posts